services:
  go-app-1:
   <<: &go-app1-config
    container_name: go-app-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - PORT=8081
      - DB_HOST=localhost
    depends_on:
      - postgres-db
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: '0.5GB'
  go-app-2:
    <<: *go-app1-config
    container_name: go-app-2
    environment:
      - LOG_LEVEL=INFO
      - PORT=8082
      - DB_HOST=localhost
  nginx:
    container_name: nginx
    image: nginx:1.27.1-alpine
    volumes:
      - ./nginx.linux.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-app-1
      - go-app-2
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: '0.5GB'
  postgres-db:
    image: postgres:16.4-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: people
      POSTGRES_PORT: 5432
    network_mode: "host"
    volumes:
    - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "max_connections=100", "-c", "log_min_error_statement=fatal", "-c", "shared_buffers=512MB"]
    deploy:
      resources:
        limits:
          cpus: '1.125'
          memory: '1.5GB'