version: '3.8'
services:
  go-backend-app-1:
   <<: &go-backend-app1-config
    container_name: go-backend-qa-app-1
    build:
      context: .
      dockerfile: Dockerfile.qa
    expose:
      - 80
    depends_on:
      - postgres-db
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  go-backend-app-2:
    <<: *go-backend-app1-config
    container_name: go-backend-qa-app-2
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-backend-app-1
      - go-backend-app-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  postgres-db:
    image: postgres:16.4-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persons
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
volumes:
  pgdata:
networks:
  qa-default:
    driver: bridge